-- This code works for PostgreSQL 16.1. If you are running on a different database management system, you will have
-- to change some parts of it

-- Database, schema and table creation should only be on the superuser side

CREATE DATABASE pleasant_vacation;

CREATE TABLE role
(
    id   SMALLINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE "user"
(
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname    VARCHAR(255) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    patronymic VARCHAR(255),
    city       VARCHAR(255) NOT NULL,
    country    VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    birthday   DATE         NOT NULL,
    image      BYTEA,
    role_id    SMALLINT     NOT NULL REFERENCES role (id)
);

-- Скидки на отдельные услуги

-- All inclusive

CREATE TABLE trip_state
(
    id   SMALLINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL
);

CREATE TABLE trip
(
    id            BIGINT         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)   NOT NULL,
    description   VARCHAR,
    city          VARCHAR(255)   NOT NULL,
    country       VARCHAR(255)   NOT NULL,
    start_date    DATE           NOT NULL,
    end_date      DATE           NOT NULL,
    price         DECIMAL(12, 2) NOT NULL,
    all_inclusive BOOL           NOT NULL,
    state_id      SMALLINT       NOT NULL REFERENCES trip_state (id)
);

CREATE TABLE review
(
    id      BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT        NOT NULL REFERENCES "user" (id),
    trip_id BIGINT        NOT NULL REFERENCES trip (id),
    date    TIMESTAMP     NOT NULL,
    text    VARCHAR(5000) NOT NULL,
    rating  SMALLINT      NOT NULL CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE ticket_state
(
    id   SMALLINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL
);

CREATE TABLE ticket
(
    id       BIGINT   NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT   NOT NULL REFERENCES "user" (id),
    trip_id  BIGINT   NOT NULL REFERENCES trip (id),
    state_id SMALLINT NOT NULL REFERENCES ticket_state (id)
);

-- It is recommended to create a user with limited rights after creating tables
-- to prevent unexpected actions (such as deleting a table).

INSERT INTO role (name)
VALUES ('ADMIN'),
       ('USER');

INSERT INTO trip_state (name)
VALUES ('ACTIVE'),
       ('INACTIVE');

INSERT INTO ticket_state (name)
VALUES ('PENDING'),
       ('ORDERED'),
       ('EXECUTED'),
       ('UNFULFILLED'),
       ('REJECTED');